# Small powerscript code to generate additional weather stations w/pheno series to an IdrAgra v2 project - used to check if the code supports having a certain number stations

param(
    [Parameter(Position = 0)]
    [ValidateRange(2, 2000)]
    [int]$Count = 120
)

$ErrorActionPreference = 'Stop'
$demoRoot = $PSScriptRoot
$meteoDir = Join-Path $demoRoot 'meteodata'
$phenoDir = Join-Path $demoRoot 'pheno'
$stationList = Join-Path $demoRoot 'weather_stations.dat'
$parameterFile = Join-Path $demoRoot 'idragra_parameters.txt'
$weatherTemplate = (Resolve-Path (Join-Path $meteoDir 'station_west.dat')).Path
$phenoTemplate = (Resolve-Path (Join-Path $phenoDir 'pheno_station_west')).Path

# Only remove files and directories generated by this script. The two original
# stations and all other demo inputs are left untouched.
Get-ChildItem -LiteralPath $meteoDir -File | Where-Object {
    $_.Name -match '^\d+\.dat$'
} | Remove-Item -Force

Get-ChildItem -LiteralPath $phenoDir -Directory | Where-Object {
    $_.Name -match '^pheno_\d+$'
} | Remove-Item -Recurse -Force

$rows = [System.Collections.Generic.List[string]]::new()
$rows.Add('# Weather stations used by the file-handle stress demo')
$rows.Add("StatNum = $Count")
$rows.Add('Table =')
$rows.Add('FileName X Y')
$rows.Add('station_west.dat 500250.0 5000750.0')
$rows.Add('station_east.dat 502000.0 5001000.0')

for ($stationIndex = 3; $stationIndex -le $Count; $stationIndex++) {
    # Numeric names make IdrAgra use this value as the unique station ID. The
    # data remain identical to station_west, which is intentional for this test.
    $stationId = 1000 + $stationIndex
    $weatherName = "$stationId.dat"
    $weatherPath = Join-Path $meteoDir $weatherName
    New-Item -ItemType HardLink -Path $weatherPath -Target $weatherTemplate | Out-Null

    $stationPhenoDir = Join-Path $phenoDir "pheno_$stationId"
    New-Item -ItemType Directory -Path $stationPhenoDir | Out-Null
    Get-ChildItem -LiteralPath $phenoTemplate -File | ForEach-Object {
        $target = Join-Path $stationPhenoDir $_.Name
        New-Item -ItemType HardLink -Path $target -Target $_.FullName | Out-Null
    }

    $rows.Add("$weatherName 500250.0 5000750.0")
}

Set-Content -LiteralPath $stationList -Value $rows -Encoding ascii

$parameters = Get-Content -LiteralPath $parameterFile
$parameters = $parameters -replace '^MeteoStatTotNum\s*=.*$', "MeteoStatTotNum = $Count"
Set-Content -LiteralPath $parameterFile -Value $parameters -Encoding ascii

$stationFiles = (Get-ChildItem -LiteralPath $meteoDir -File).Count
$phenologyFiles = (Get-ChildItem -LiteralPath $phenoDir -File -Recurse).Count
$expectedPersistent = 9 * $Count
Write-Host "Configured $Count stations."
Write-Host "Station-related persistent files expected during simulation: $expectedPersistent"
Write-Host "Weather files present: $stationFiles; phenology files present: $phenologyFiles"
Write-Host 'MeteoStatWeightNum remains 2, so added stations do not alter spatial interpolation.'
