program main
use mod_utility, only: lower_case, print_execution_time
use mod_parameters, only: parameters, water_sources_table, source_info
use mod_grid, only: write_grid, min_domain, bound      ! variables and methods to handle spatial input
use mod_meteo!, only: meteo_series_length, read_meteo_parameters,
    ! close_meteo_file, read_meteo_data
use mod_TDx_index                                     ! variables and methods to handle meteorological data

use cli_crop_parameters, only: init_crop_phenology_pars, destroy_info_pheno, crop_pheno_info ! variables and methods to handle crop parameters
use cli_watsources                                                          ! variables and methods to handle irrigation units water supply
use cli_simulation_manager                                                  ! simulation manager: control IO and daily cycle
use cli_read_parameter

use mod_system
implicit none


type(parameters) :: xml                                     ! stores parameters of input file
type(TDx_index) :: xml_TDx                                  ! stores parameters of input file for TDX indices
type(bound)::boundaries                                     ! stores domain extension (rectangle)
type(spatial_info)::info_spat                               ! stores spatial inputs
type(water_sources_table),dimension(:),allocatable::watsour ! stores parameters of "<watsources>.txt" file
real(dp), dimension(10,3,4):: tab_CN2, tab_CN3               ! CN implementation
type(source_info)::info_sources                             ! stores water sources series
type(meteo_info),dimension(:),allocatable::info_meteo       ! stores meteorological series data
type(crop_pheno_info),dimension(:),allocatable::info_pheno  ! stores phenological parameters series
type(soil2_rice)::theta2_rice                               ! stores soil parameters data for paddy rice fields

integer,dimension(8)::t_start,t_stop
integer :: errorflag
character(len = 255) :: filename = 'idragra_parameters.txt'

character(len=50) :: arg
integer :: i
! default settings
logical :: verbose = .false.
logical :: summary = .false.
logical :: showpreview = .false.

! get options
do i = 1, iargc()
    call getarg(i, arg)
    if (arg(1:1)=='-') then
        call lower_case(arg)
        select case (arg)
            case ('-verbose', '-v')         ! set verbose mode: add some extra message to prompt
                verbose = .true.
            case ('-summary','-s')          ! set if only irrigation is printed
                summary = .true.
            case ('-help', '-h')            ! show help string
                call print_header()
                call show_help()
            case ('-filename', '-f')        ! set filename
                call getarg(i+1, arg)
                filename = arg
            case ('-preview', '-p')         ! show all parameters after reading configuration file
                showpreview = .true.
            case ('-default', '-d')         ! print all default value
                call print_header()
                print *, '=== DEFAULT VALUES ==='
                call print_parameters(xml,xml_TDx)
                print *, '=== END DEFAULT ==='
                stop
            case default                    ! all other cases ...
                call print_header()
                print *, 'Not supported option <',trim(arg),'>'
                call show_help()
        end select
    end if
end do

! TODO: check if there are other strings without '-', as it can be related to a skipped -f option

! set up environment options

call print_header()
! Memorization of time in which simulation starts
call date_and_time(values=t_start)

! Reads simulation input parameters
call read_all_parameters(filename, xml, xml_TDx, ErrorFlag, verbose)

if (showpreview .eqv. .true.) then
    print *, '=== PREVIEW ==='
    call print_parameters(xml, xml_TDx)
    print *, '=== END PREVIEW ==='
end if
print*,'Simulation parameters have been set'

! Evaluates simulation length [days] by counting meteorological files' lines
call meteo_series_length(xml%sim, verbose)

! Defines simulation domain boundaries
call min_domain(trim(xml%sim%input_path)//trim(xml%sim%domain_fn)//'.asc',boundaries,xml%sim)
print*,"Simulation domain boundaries have been set"

! Checks if soil initial condition is an input or it is generated by running first year of simulation
if(xml%sim%f_init_wc .eqv. .false.)then ! Generates soil initial condition

    ! Initializes info_spat and reads spatial files (*.asc); initializes tab_CN*
    call read_spatial_info(info_spat,boundaries,xml%sim,tab_CN2,tab_CN3,theta2_rice,xml%irr%met)
    print*,"Variable info_spat has been initialized"
    if (xml%sim%prt_debug_out=='y') then
        ! Print spatial data matrices in files out_*.asc
        call write_init_grids(info_spat,xml%sim%mode,xml%sim%path,xml%sim)
        print*,"Input maps have been printed"
    end if

    print *, '=== INITIAL CONDITION ==='
    ! Initializes info_meteo matrices with meteorological data
    call read_meteo_parameters(xml%sim,info_meteo,verbose)
    print*, 'Variable "info_meteo" has been initialized'

    ! Initializes info_pheno matrices (by associating file units to files)
    call init_crop_phenology_pars(xml%sim, info_pheno, info_meteo, xml%depth%ze_fix, verbose)
    print*, 'Variable "info_pheno" has been initialized'

    ! Initializes watsources and info_sources matrices
    if (xml%sim%mode == 1) then                 ! USE mode
        call init_water_sources_duty(xml,watsour,info_sources,info_meteo)
        print*, 'Variables "watsour" and "info_sources" have been initialized'
    end if

    ! Soil-crop water balance algorithm
    call simulation_manager(xml, xml_TDx, info_spat, watsour, info_sources, info_meteo, &
        & info_pheno, tab_CN2, tab_CN3, theta2_rice, 1, boundaries, verbose, summary)

    ! Prints initial condition values
    if (xml%sim%prt_init_cond == 'y') then
        call write_grid(trim(xml%sim%path)//'IC_thetaI.asc',info_spat%theta(1)%old,errorflag)
        call write_grid(trim(xml%sim%path)//'IC_thetaII.asc',info_spat%theta(2)%old,errorflag)
    end if

    ! Closes input files
    if (xml%sim%mode == 1) call close_water_sources_dudy(info_sources,xml)        ! USE mode
    call close_meteo_file(info_meteo)
    call destroy_info_pheno(info_pheno)
    print *, '=== INITIAL CONDITION SET ==='
end if

! Initializes info_spat and reads spatial files (*.asc); initializes tab_CN*
call read_spatial_info(info_spat,boundaries,xml%sim,tab_CN2,tab_CN3,theta2_rice,xml%irr%met)
print*,"Variable info_spat has been initialized"
if (xml%sim%prt_debug_out=='y') then
    ! Print spatial data matrices in files out_*.asc
    call write_init_grids(info_spat,xml%sim%mode,xml%sim%path,xml%sim)
    print*,"Input maps have been printed"
end if

! %EAC%: add filter to limit water table to evaporative layer
where(info_spat%wat_tab%mat<xml%depth%ze_fix .and. &
    info_spat%wat_tab%mat/=info_spat%wat_tab%header%nan)
    info_spat%wat_tab%mat=xml%depth%ze_fix
end where

! Initializes info_meteo matrices with meteorological data
call read_meteo_parameters(xml%sim,info_meteo,verbose)
print*, 'Variable "info_meteo" has been initialized'

! Initializes info_pheno matrices (by associating file units to files)
call init_crop_phenology_pars(xml%sim, info_pheno, info_meteo, xml%depth%ze_fix, verbose)
print*, 'Variable "info_pheno" has been initialized'

! Initializes watsources and info_sources matrices
if (xml%sim%mode == 1) then         ! %AB% USE mode
    call init_water_sources_duty(xml,watsour,info_sources, info_meteo)
    print*, 'Variables "watsources" and "info_sources" have been initialized'
end if

! Soil-crop water balance algorithm
print*,"=== SIMULATION ==="
call simulation_manager(xml,xml_TDx,info_spat,watsour,info_sources,info_meteo,info_pheno, tab_CN2, tab_CN3, &
    & theta2_rice,xml%sim%sim_years,boundaries,verbose, summary)

! Closes input files
if (xml%sim%mode == 1) call close_water_sources_dudy(info_sources,xml)        ! USE mode
call close_meteo_file(info_meteo)
call destroy_info_pheno(info_pheno)

! Memorization of time in which simulation ends
call date_and_time(values=t_stop)

! Prints simulation computing time
call print_execution_time(t_start, t_stop)

end program main

subroutine show_help()
print *, 'List of options:'
print *, '-h, -help: return some helpful information'
print *, '-d, -default: print default input values'
print *, '-p, -preview: show all parameters after reading configuration files'
print *, '-t, -teta, -theta: print soil water content at the end of each year'
print *, '-v, -verbose: print all outputs'
print *, '-s, -summary: print only irrigation - both annual and periodical - outputs'
print *, '-f, -filename <parameters> : use file <parameters> to pass settings'
print *, '====================='
! stop execution because of a possible error
stop
end subroutine show_help

subroutine print_header()
! use makefile macros to set version and compilation timestamp
print *, '============== IDRAGRA - IDRologia AGRAria ================'
print *, 'contact: claudio.gandolfi@unimi.it'
print *, 'code version: ',GIT_VERSION
print *, 'compiled on: ',COMP_DATE
print *, 'source available on https://github.com/rita-tools/IdrAgra_v2'
print *, '============================================================'
print *, ''
end subroutine print_header

subroutine print_parameters(xml,xml_dtx)
use mod_parameters, only: parameters
use mod_TDx_index, only: TDx_index
type(parameters), intent(in) :: xml
type(TDx_index), intent(in) :: xml_dtx

print *,'OutputPath = ',  xml%sim%path
print *,'MeteoPath = ', xml%sim%meteo_path
print *,'MeteoFileName = ', xml%sim%ws_list_fn
print *,'PhenoPath = ', xml%sim%pheno_path
print *,'PhenoFileRoot = ', xml%sim%pheno_root
print *,'IrrMethPath = ', xml%sim%irr_met_path
print *,'IrrMethFileName = ', xml%sim%irr_met_list_fn
print *,'WatSourpath = ', xml%sim%watsour_path
print *,'InitialCondition = ', xml%sim%initial_condition
print *,'FinalCondition = ', xml%sim%final_condition
! spatial inputs
print *, 'domFileName = ', xml%sim%domain_fn
print *, 'tetaI_FCFileName = ', xml%sim%thetaI_FC_fn
print *, 'tetaII_FCFileName = ', xml%sim%thetaII_FC_fn
print *, 'tetaI_WPFileName = ', xml%sim%thetaI_WP_fn
print *, 'tetaII_WPFileName = ', xml%sim%thetaII_WP_fn
print *, 'tetaI_rFileName = ', xml%sim%thetaI_r_fn
print *, 'tetaII_rFileName = ', xml%sim%thetaII_r_fn
print *, 'tetaI_SATFileName = ', xml%sim%thetaI_SAT_fn
print *, 'tetaII_SATFileName = ', xml%sim%thetaII_SAT_fn
print *, 'slopeFileName = ', xml%sim%slope_fn
print *, 'drenFileName = ', xml%sim%dren_fn
print *, 'hydr_grFileName = ', xml%sim%hydr_group_fn
print *, 'ksat_IFileName = ', xml%sim%ksat_I_fn
print *, 'ksat_IIFileName = ', xml%sim%ksat_II_fn
print *, 'n_IFileName = ', xml%sim%n_I_fn
print *, 'n_IIFileName = ', xml%sim%n_II_fn
print *, 'thetaI_0FileName = ', xml%sim%thetaI_0_fn
print *, 'thetaII_0FileName = ', xml%sim%thetaII_0_fn
print *, 'paddy_soil_FileName = ', xml%sim%soil_prop_x_rice_fn
print *, 'eff_metodoFileName = ', xml%sim%eff_irr_fn
print *, 'eff_reteFileName = ', xml%sim%eff_net_fn
print *, 'irr_unitsFileName = ', xml%sim%irr_units_fn
print *, 'irr_methFileName = ', xml%sim%id_irr_meth_fn
print *, 'water_table_depth_FileName = ' , xml%sim%wat_table_fn
print *, 'ParRisCap_a3FileName = ', xml%sim%ParRisCap_a3_fn
print *, 'ParRisCap_a4FileName = ', xml%sim%ParRisCap_a4_fn
print *, 'ParRisCap_b1FileName = ', xml%sim%ParRisCap_b1_fn
print *, 'ParRisCap_b2FileName = ', xml%sim%ParRisCap_b2_fn
print *, 'ParRisCap_b3FileName = ', xml%sim%ParRisCap_b3_fn
print *, 'ParRisCap_b4FileName = ', xml%sim%ParRisCap_b4_fn
print *, 'ShapeAreaFlag = '       , xml%sim%f_shapearea
print *, 'ShapeAreaFileName = '   , xml%sim%shapearea_fn
print *, 'iRandomFileName = '     , xml%sim%irandom_fn

print *, 'mode = ',  xml%sim%mode
print *, 'mflag = ',  xml%sim%step_out
print *, 'time = ', xml%sim%clock
print *, 'InitialThetaFlag = ',  xml%sim%f_init_wc
print *, 'FinalThetaFlag = ',  xml%sim%f_theta_out
print *, 'RadnSowDaysWind = ',  xml%sim%sowing_range
print *, 'SoilUsesNum = ', xml%sim%n_lus
print *, 'CapillaryFlag = ', xml%sim%f_cap_rise
print *, 'SoilUseVarFlag = ', xml%sim%f_soiluse
print *, 'MeteoStatWeightNum = ', xml%sim%n_ws
print *, 'MeteoStatTotNum = ', xml%sim%n_voronoi
print *, 'InterpolateTemperature = ', xml%sim%interpolate_temp
print *, 'InterpolateRain = ', xml%sim%interpolate_rain
print *, 'InterpolateHumidity = ', xml%sim%interpolate_hum
print *, 'InterpolateWind = ', xml%sim%interpolate_wind
print *, 'InterpolateRadiation = ', xml%sim%interpolate_rad
print *, 'forecast_day = ', xml%sim%forecast_day
print *, 'zEvap = ', xml%depth%ze_fix
print *, 'zRoot = ', xml%depth%zr_fix
print *, 'LambdaCN = ', xml%sim%lambda_cn
print *, 'StartIrrSeason = ', xml%sim%start_irr_season
print *, 'EndIrrSeason = ', xml%sim%end_irr_season
print *, 'h_maxpond', xml%sim%h_maxpond
print *, 'DTxMode =',xml_dtx%mode
print *, 'DTxNumXs=',xml_dtx%temp%n_ind
print *, 'DTx_X=',xml_dtx%temp%x
print *, 'DTxDeltaDate=',xml_dtx%temp%td
print *, 'DTxDelayDays=',xml_dtx%temp%delay
print *, 'DTxMinCard=',xml_dtx%n
end subroutine print_parameters
