name: Makefile CI

#on:
#  push:
#    tags:
#      - "v*"

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make

      - uses: actions/upload-artifact@v4
        with:
          name: idragra
          path: release/idragra.exe
    
      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     prerelease: false
      #     automatic_release_tag: latest

